server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /dobetter
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*


friend:
  name: wang